# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tab1.setObjectName("tab1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_loadFile = QtWidgets.QPushButton(self.tab1)
        self.pushButton_loadFile.setObjectName("pushButton_loadFile")
        self.horizontalLayout_6.addWidget(self.pushButton_loadFile)
        self.pushButton_clearMarkers = QtWidgets.QPushButton(self.tab1)
        self.pushButton_clearMarkers.setObjectName("pushButton_clearMarkers")
        self.horizontalLayout_6.addWidget(self.pushButton_clearMarkers)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.listWidget = QtWidgets.QListWidget(self.tab1)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_forward = QtWidgets.QPushButton(self.tab2)
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.gridLayout_2.addWidget(self.pushButton_forward, 0, 1, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(self.tab2)
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout_2.addWidget(self.pushButton_left, 1, 0, 1, 1)
        self.pushButton_backword = QtWidgets.QPushButton(self.tab2)
        self.pushButton_backword.setObjectName("pushButton_backword")
        self.gridLayout_2.addWidget(self.pushButton_backword, 1, 1, 1, 1)
        self.pushButton_right = QtWidgets.QPushButton(self.tab2)
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout_2.addWidget(self.pushButton_right, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsView_camera = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_camera.setObjectName("graphicsView_camera")
        self.verticalLayout_6.addWidget(self.graphicsView_camera)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_Compass = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsView_Compass.sizePolicy().hasHeightForWidth())
        self.graphicsView_Compass.setSizePolicy(sizePolicy)
        self.graphicsView_Compass.setSizeIncrement(QtCore.QSize(1, 1))
        self.graphicsView_Compass.setBaseSize(QtCore.QSize(1, 1))
        self.graphicsView_Compass.setObjectName("graphicsView_Compass")
        self.verticalLayout.addWidget(self.graphicsView_Compass)
        self.pushButton_belt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_belt.setObjectName("pushButton_belt")
        self.verticalLayout.addWidget(self.pushButton_belt)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label_right_motor = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_right_motor.sizePolicy().hasHeightForWidth())
        self.label_right_motor.setSizePolicy(sizePolicy)
        self.label_right_motor.setObjectName("label_right_motor")
        self.gridLayout.addWidget(self.label_right_motor, 5, 0, 1, 1)
        self.label_heading = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_heading.sizePolicy().hasHeightForWidth())
        self.label_heading.setSizePolicy(sizePolicy)
        self.label_heading.setObjectName("label_heading")
        self.gridLayout.addWidget(self.label_heading, 0, 0, 1, 1)
        self.label_battery_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_battery_info.sizePolicy().hasHeightForWidth())
        self.label_battery_info.setSizePolicy(sizePolicy)
        self.label_battery_info.setObjectName("label_battery_info")
        self.gridLayout.addWidget(self.label_battery_info, 2, 1, 1, 1)
        self.label_right_motor_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_right_motor_info.sizePolicy().hasHeightForWidth())
        self.label_right_motor_info.setSizePolicy(sizePolicy)
        self.label_right_motor_info.setObjectName("label_right_motor_info")
        self.gridLayout.addWidget(self.label_right_motor_info, 5, 1, 1, 1)
        self.label_speed = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_speed.sizePolicy().hasHeightForWidth())
        self.label_speed.setSizePolicy(sizePolicy)
        self.label_speed.setObjectName("label_speed")
        self.gridLayout.addWidget(self.label_speed, 4, 0, 1, 1)
        self.label_coords = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_coords.sizePolicy().hasHeightForWidth())
        self.label_coords.setSizePolicy(sizePolicy)
        self.label_coords.setObjectName("label_coords")
        self.gridLayout.addWidget(self.label_coords, 1, 0, 1, 1)
        self.label_coords_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_coords_info.sizePolicy().hasHeightForWidth())
        self.label_coords_info.setSizePolicy(sizePolicy)
        self.label_coords_info.setObjectName("label_coords_info")
        self.gridLayout.addWidget(self.label_coords_info, 1, 1, 1, 1)
        self.label_speed_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_speed_info.sizePolicy().hasHeightForWidth())
        self.label_speed_info.setSizePolicy(sizePolicy)
        self.label_speed_info.setObjectName("label_speed_info")
        self.gridLayout.addWidget(self.label_speed_info, 4, 1, 1, 1)
        self.label_storage_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_storage_info.sizePolicy().hasHeightForWidth())
        self.label_storage_info.setSizePolicy(sizePolicy)
        self.label_storage_info.setObjectName("label_storage_info")
        self.gridLayout.addWidget(self.label_storage_info, 3, 1, 1, 1)
        self.label_storage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_storage.sizePolicy().hasHeightForWidth())
        self.label_storage.setSizePolicy(sizePolicy)
        self.label_storage.setObjectName("label_storage")
        self.gridLayout.addWidget(self.label_storage, 3, 0, 1, 1)
        self.label_battery = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_battery.sizePolicy().hasHeightForWidth())
        self.label_battery.setSizePolicy(sizePolicy)
        self.label_battery.setObjectName("label_battery")
        self.gridLayout.addWidget(self.label_battery, 2, 0, 1, 1)
        self.label_left_motor = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_left_motor.sizePolicy().hasHeightForWidth())
        self.label_left_motor.setSizePolicy(sizePolicy)
        self.label_left_motor.setObjectName("label_left_motor")
        self.gridLayout.addWidget(self.label_left_motor, 6, 0, 1, 1)
        self.label_1left_motor_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1left_motor_info.sizePolicy().hasHeightForWidth())
        self.label_1left_motor_info.setSizePolicy(sizePolicy)
        self.label_1left_motor_info.setObjectName("label_1left_motor_info")
        self.gridLayout.addWidget(self.label_1left_motor_info, 6, 1, 1, 1)
        self.label_heading_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_heading_info.sizePolicy().hasHeightForWidth())
        self.label_heading_info.setSizePolicy(sizePolicy)
        self.label_heading_info.setObjectName("label_heading_info")
        self.gridLayout.addWidget(self.label_heading_info, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 10)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUser_Manual = QtWidgets.QAction(MainWindow)
        self.actionUser_Manual.setObjectName("actionUser_Manual")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.menuHelp.addAction(self.actionUser_Manual)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Us)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Garbage Collecting Boat"))
        self.pushButton_loadFile.setText(_translate("MainWindow", "Load From File"))
        self.pushButton_clearMarkers.setText(_translate("MainWindow", "Clear All Markers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Fix-Route Mode"))
        self.pushButton_forward.setText(_translate("MainWindow", "Forward"))
        self.pushButton_left.setText(_translate("MainWindow", "Left"))
        self.pushButton_backword.setText(_translate("MainWindow", "Backword"))
        self.pushButton_right.setText(_translate("MainWindow", "Right"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Manual Mode"))
        self.pushButton_belt.setText(_translate("MainWindow", "Conveyor Belt On"))
        self.label_right_motor.setText(_translate("MainWindow", "Right Motor Load"))
        self.label_heading.setText(_translate("MainWindow", "Heading"))
        self.label_battery_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_right_motor_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_speed.setText(_translate("MainWindow", "Speed"))
        self.label_coords.setText(_translate("MainWindow", "Coords"))
        self.label_coords_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_speed_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_storage_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_storage.setText(_translate("MainWindow", "Storage Room"))
        self.label_battery.setText(_translate("MainWindow", "Battery Level"))
        self.label_left_motor.setText(_translate("MainWindow", "Left Motor Load"))
        self.label_1left_motor_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_heading_info.setText(_translate("MainWindow", "TextLabel"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionUser_Manual.setText(_translate("MainWindow", "User Manual"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))

