# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1004, 607)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView_map = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_map.setObjectName("graphicsView_map")
        self.verticalLayout_2.addWidget(self.graphicsView_map)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tab1.setObjectName("tab1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_7.addWidget(self.lineEdit)
        self.listView = QtWidgets.QListView(self.tab1)
        self.listView.setObjectName("listView")
        self.verticalLayout_7.addWidget(self.listView)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_add = QtWidgets.QPushButton(self.tab1)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout_8.addWidget(self.pushButton_add)
        self.pushButton_delete = QtWidgets.QPushButton(self.tab1)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.verticalLayout_8.addWidget(self.pushButton_delete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_forward = QtWidgets.QPushButton(self.tab2)
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.gridLayout_2.addWidget(self.pushButton_forward, 0, 1, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(self.tab2)
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout_2.addWidget(self.pushButton_left, 1, 0, 1, 1)
        self.pushButton_backword = QtWidgets.QPushButton(self.tab2)
        self.pushButton_backword.setObjectName("pushButton_backword")
        self.gridLayout_2.addWidget(self.pushButton_backword, 1, 1, 1, 1)
        self.pushButton_right = QtWidgets.QPushButton(self.tab2)
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout_2.addWidget(self.pushButton_right, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsView_camera = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_camera.setObjectName("graphicsView_camera")
        self.verticalLayout_6.addWidget(self.graphicsView_camera)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_Compass = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsView_Compass.sizePolicy().hasHeightForWidth())
        self.graphicsView_Compass.setSizePolicy(sizePolicy)
        self.graphicsView_Compass.setSizeIncrement(QtCore.QSize(1, 1))
        self.graphicsView_Compass.setBaseSize(QtCore.QSize(1, 1))
        self.graphicsView_Compass.setObjectName("graphicsView_Compass")
        self.verticalLayout.addWidget(self.graphicsView_Compass)
        self.pushButton_belt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_belt.setObjectName("pushButton_belt")
        self.verticalLayout.addWidget(self.pushButton_belt)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_right_motor = QtWidgets.QLabel(self.centralwidget)
        self.label_right_motor.setObjectName("label_right_motor")
        self.gridLayout.addWidget(self.label_right_motor, 5, 0, 1, 1)
        self.label_heading = QtWidgets.QLabel(self.centralwidget)
        self.label_heading.setObjectName("label_heading")
        self.gridLayout.addWidget(self.label_heading, 0, 0, 1, 1)
        self.label_battery_info = QtWidgets.QLabel(self.centralwidget)
        self.label_battery_info.setObjectName("label_battery_info")
        self.gridLayout.addWidget(self.label_battery_info, 2, 1, 1, 1)
        self.label_right_motor_info = QtWidgets.QLabel(self.centralwidget)
        self.label_right_motor_info.setObjectName("label_right_motor_info")
        self.gridLayout.addWidget(self.label_right_motor_info, 5, 1, 1, 1)
        self.label_speed = QtWidgets.QLabel(self.centralwidget)
        self.label_speed.setObjectName("label_speed")
        self.gridLayout.addWidget(self.label_speed, 4, 0, 1, 1)
        self.label_coords = QtWidgets.QLabel(self.centralwidget)
        self.label_coords.setObjectName("label_coords")
        self.gridLayout.addWidget(self.label_coords, 1, 0, 1, 1)
        self.label_coords_info = QtWidgets.QLabel(self.centralwidget)
        self.label_coords_info.setObjectName("label_coords_info")
        self.gridLayout.addWidget(self.label_coords_info, 1, 1, 1, 1)
        self.label_speed_info = QtWidgets.QLabel(self.centralwidget)
        self.label_speed_info.setObjectName("label_speed_info")
        self.gridLayout.addWidget(self.label_speed_info, 4, 1, 1, 1)
        self.label_storage_info = QtWidgets.QLabel(self.centralwidget)
        self.label_storage_info.setObjectName("label_storage_info")
        self.gridLayout.addWidget(self.label_storage_info, 3, 1, 1, 1)
        self.label_storage = QtWidgets.QLabel(self.centralwidget)
        self.label_storage.setObjectName("label_storage")
        self.gridLayout.addWidget(self.label_storage, 3, 0, 1, 1)
        self.label_battery = QtWidgets.QLabel(self.centralwidget)
        self.label_battery.setObjectName("label_battery")
        self.gridLayout.addWidget(self.label_battery, 2, 0, 1, 1)
        self.label_left_motor = QtWidgets.QLabel(self.centralwidget)
        self.label_left_motor.setObjectName("label_left_motor")
        self.gridLayout.addWidget(self.label_left_motor, 6, 0, 1, 1)
        self.label_1left_motor_info = QtWidgets.QLabel(self.centralwidget)
        self.label_1left_motor_info.setObjectName("label_1left_motor_info")
        self.gridLayout.addWidget(self.label_1left_motor_info, 6, 1, 1, 1)
        self.label_heading_info = QtWidgets.QLabel(self.centralwidget)
        self.label_heading_info.setObjectName("label_heading_info")
        self.gridLayout.addWidget(self.label_heading_info, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.tabWidget.raise_()
        self.graphicsView_camera.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Garbage Collecting Boat"))
        self.pushButton_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_delete.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Fix-Route Mode"))
        self.pushButton_forward.setText(_translate("MainWindow", "Forward"))
        self.pushButton_left.setText(_translate("MainWindow", "Left"))
        self.pushButton_backword.setText(_translate("MainWindow", "Backword"))
        self.pushButton_right.setText(_translate("MainWindow", "Right"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Manual Mode"))
        self.pushButton_belt.setText(_translate("MainWindow", "Conveyor Belt On"))
        self.label_right_motor.setText(_translate("MainWindow", "Right Motor Load"))
        self.label_heading.setText(_translate("MainWindow", "Heading"))
        self.label_battery_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_right_motor_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_speed.setText(_translate("MainWindow", "Speed"))
        self.label_coords.setText(_translate("MainWindow", "Coords"))
        self.label_coords_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_speed_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_storage_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_storage.setText(_translate("MainWindow", "Storage Room"))
        self.label_battery.setText(_translate("MainWindow", "Battery Level"))
        self.label_left_motor.setText(_translate("MainWindow", "Left Motor Load"))
        self.label_1left_motor_info.setText(_translate("MainWindow", "TextLabel"))
        self.label_heading_info.setText(_translate("MainWindow", "TextLabel"))

